/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.NhanVien;
import ServiceNhanVien.nhanVienService;
import java.util.ArrayList;
import view.FormTrangChu;

public class FormNhanVien extends javax.swing.JPanel {

    private int index = -1;
    private nhanVienService service = new nhanVienService();
    DefaultTableModel molTable = new DefaultTableModel();
    DefaultTableModel molTableTim = new DefaultTableModel();

    /**
     * Creates new form FormNhanVien
     */
    public FormNhanVien() {
        initComponents();
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_CLEAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ngayDK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rdo_dangLam = new javax.swing.JRadioButton();
        rdo_daNghi = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rdo_nv = new javax.swing.JRadioButton();
        rdo_ql = new javax.swing.JRadioButton();
        txt_pass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txt_ngaySua = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listNV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txt_find = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên ");

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        btn_add.setText("THEM");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setText("SUA");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_CLEAR.setText("CLEAR");
        btn_CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CLEARActionPerformed(evt);
            }
        });

        jLabel3.setText("TEN NHAN VIEN");

        jLabel4.setText("GIOI TINH");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setText("NAM");
        rdo_nam.setSelected(true);

        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("NU");

        jLabel5.setText("EMAIL");

        jLabel6.setText("SDT");

        jLabel7.setText("NGAY TAO");

        txt_ngayDK.setEditable(false);

        jLabel8.setText("USER NAME");

        jLabel9.setText("PASSWORD");

        jLabel10.setText("TRANG THAI");

        buttonGroup2.add(rdo_dangLam);
        rdo_dangLam.setText("DANG LAM");
        rdo_dangLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_dangLamActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdo_daNghi);
        rdo_daNghi.setText("DA NGHI");

        jLabel11.setText("VAI TRO");

        buttonGroup3.add(rdo_nv);
        rdo_nv.setText("NHAN VIEN");

        buttonGroup3.add(rdo_ql);
        rdo_ql.setText("QUAN LY");

        jLabel12.setText("NGAY SUA");

        txt_ngaySua.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        tbl_listNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "HO VA TEN", "GIOI TINH", "EMAIL", "SDT", "NGAY TAO", "NGAY SUA", "USER NAME", "PASSWORD", "TRANG THAI", "VAI TRO"
            }
        ));
        tbl_listNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_listNV);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txt_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_findActionPerformed(evt);
            }
        });
        txt_find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_findKeyPressed(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_add)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_update)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_CLEAR))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rdo_nam)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rdo_nu))
                                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                    .addComponent(txt_ten)
                                                    .addComponent(txt_id)
                                                    .addComponent(txt_sdt)))
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rdo_nv)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(rdo_ql))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rdo_dangLam)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rdo_daNghi))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txt_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                        .addComponent(txt_pass))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txt_ngayDK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel12)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_ngaySua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txt_ngayDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_ngaySua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdo_nam)
                    .addComponent(rdo_nu)
                    .addComponent(jLabel9)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(rdo_dangLam)
                    .addComponent(rdo_daNghi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rdo_nv)
                    .addComponent(rdo_ql))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(btn_CLEAR))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_listNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listNVMouseClicked
        try {
            index = tbl_listNV.getSelectedRow();
            if (txt_find.getText().trim().isEmpty()) {
                this.showNhanVien(index);
            } else {
                this.showFindNhanVien(index);
            }
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbl_listNVMouseClicked

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        for (NhanVien nv : service.findAll()) {
            if (nv.getEmail().equals(txt_email.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Email đã tồn tại, vui lòng nhập email khác");
                return ;
            }
            if (nv.getSdt().equals(txt_sdt.getText().trim())) {
                JOptionPane.showMessageDialog(this, "SĐT đã tồn tại, vui lòng nhập SĐT khác");
                return ;
            }
            if (nv.getUserName().equals(txt_userName.getText().trim())) {
                JOptionPane.showMessageDialog(this, "UserName đã tồn tại, vui lòng nhập UserName khác");
                return;
            }
        }
        try {
            if (checkvalidate()) {
                NhanVien nv = add();
                if (service.add(nv) != null) {
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                    this.fillTable();
                    this.btn_CLEARActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e);
            System.out.println("Thêm lỗi ở hệ thống");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        index = tbl_listNV.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa");
            return;
        }
        try {
            NhanVien nv = this.update();
            if (checkvalidate()) {
                if (service.update(nv) != null) {
                    JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công");
                    this.fillTable();
                    this.btn_CLEARActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Sdt, Email, UserName đã tồn tại");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txt_find.getText().trim().isEmpty()) {
            fillTable();
        } else {
            if (service.findNhanVien(txt_find.getText().trim(), txt_find.getText().trim()) == null) {
                JOptionPane.showMessageDialog(this, "Không tìm được nhân viên");
                fillTable();
            }else{
                fillTableTK();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CLEARActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_ten.setText("");
        txt_email.setText("");
        txt_find.setText("");
        txt_ngayDK.setText("");
        txt_ngaySua.setText("");
        txt_pass.setText("");
        txt_userName.setText("");
        txt_sdt.setText("");
        rdo_nam.setSelected(true);
        rdo_dangLam.setSelected(true);
        rdo_nv.setSelected(true);
    }//GEN-LAST:event_btn_CLEARActionPerformed

    private void txt_findKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_findKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_findKeyPressed

    private void rdo_dangLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_dangLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_dangLamActionPerformed

    private void txt_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_findActionPerformed

    private void fillTable() {
        molTable = (DefaultTableModel) tbl_listNV.getModel();
        molTable.setRowCount(0);
        List<NhanVien> list = null;
        String find = txt_find.getText().trim();
        list = service.findAll();
        for (NhanVien nv : list) {
            molTable.addRow(nv.toDataRow());
        }

    }

    private void fillTableTK() {
        molTableTim = (DefaultTableModel) tbl_listNV.getModel();
        molTableTim.setRowCount(0);
        String find = txt_find.getText().trim();
        ArrayList<NhanVien> list = service.findNhanVien(find, find);
        for (NhanVien nv : list) {
            molTable.addRow(nv.toDataRow());
        }
    }

    void timKiem() {
        this.fillTableTK();
    }

    private void showNhanVien(int index) {
        NhanVien nv = service.findAll().get(index);
        txt_id.setText(String.valueOf(nv.getId()));
        txt_ten.setText(nv.getTenNhanVien());
        if (nv.isGioiTinh() == true) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }
        txt_email.setText(nv.getEmail());
        txt_sdt.setText(nv.getSdt());
        txt_ngayDK.setText(String.valueOf(nv.getNgayTao()));
        txt_ngaySua.setText(String.valueOf(nv.getNgaySua()));
        txt_userName.setText(nv.getUserName());
        txt_pass.setText(nv.getPassWord());
        if (nv.isTrangThai() == true) {
            rdo_dangLam.setSelected(true);
        } else {
            rdo_daNghi.setSelected(true);
        }
        if (nv.isVaiTro() == true) {
            rdo_ql.setSelected(true);
        } else {
            rdo_nv.setSelected(true);
        }
    }

    private void showFindNhanVien(int index) {
        String find = txt_find.getText().trim();
        NhanVien nv = service.findNhanVien(find, find).get(index);
        txt_id.setText(String.valueOf(nv.getId()));
        txt_ten.setText(nv.getTenNhanVien());
        if (nv.isGioiTinh() == true) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }
        txt_email.setText(nv.getEmail());
        txt_sdt.setText(nv.getSdt());
        txt_ngayDK.setText(String.valueOf(nv.getNgayTao()));
        txt_ngaySua.setText(String.valueOf(nv.getNgaySua()));
        txt_userName.setText(nv.getUserName());
        txt_pass.setText(nv.getPassWord());
        if (nv.isTrangThai() == true) {
            rdo_dangLam.setSelected(true);
        } else {
            rdo_daNghi.setSelected(true);
        }
        if (nv.isVaiTro() == true) {
            rdo_ql.setSelected(true);
        } else {
            rdo_nv.setSelected(true);
        }
    }

    private NhanVien update() {
        NhanVien nv = new NhanVien();
        nv.setId(Integer.valueOf(txt_id.getText()));
        nv.setTenNhanVien(txt_ten.getText().trim());
        nv.setEmail(txt_email.getText().trim());
        if (rdo_nam.isSelected()) {
            nv.setGioiTinh(true);
        } else {
            nv.setGioiTinh(false);
        }
        nv.setSdt(txt_sdt.getText().trim());
        nv.setUserName(txt_userName.getText().trim());
        nv.setPassWord(new String(txt_pass.getPassword()));
        if (rdo_dangLam.isSelected()) {
            nv.setTrangThai(true);
        } else {
            nv.setTrangThai(false);
        }
        if (rdo_ql.isSelected()) {
            nv.setVaiTro(true);
        } else {
            nv.setVaiTro(false);
        }
        return nv;
    }

    private NhanVien add() {
        NhanVien nv = new NhanVien();
        nv.setTenNhanVien(txt_ten.getText().trim());
        nv.setEmail(txt_email.getText().trim());
        if (rdo_nam.isSelected()) {
            nv.setGioiTinh(true);
        } else {
            nv.setGioiTinh(false);
        }
        nv.setSdt(txt_sdt.getText().trim());
        nv.setUserName(txt_userName.getText().trim());
        nv.setPassWord(new String(txt_pass.getPassword()));
        if (rdo_dangLam.isSelected()) {
            nv.setTrangThai(true);
        } else {
            nv.setTrangThai(false);
        }
        if (rdo_ql.isSelected()) {
            nv.setVaiTro(true);
        } else {
            nv.setVaiTro(false);
        }
        return nv;
    }

    boolean checkvalidate() {
        try {
            if (txt_ten.getText().equals("")) {
                txt_ten.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Họ và tên");
                return false;
            }
            if (!txt_ten.getText().matches("^[\\p{L}\\s'-]+$")) {
                txt_ten.requestFocus();
                JOptionPane.showMessageDialog(this, "Tên không chứa kí tự đặc biệt");
                return false;
            }
            if (txt_email.getText().trim().isEmpty()) {
                txt_email.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Email");
                return false;
            }
            if (txt_sdt.getText().trim().isEmpty()) {
                txt_sdt.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Sdt");
                return false;
            }
            if (txt_userName.getText().trim().isEmpty()) {
                txt_userName.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập UserName");
                return false;
            }
            if (txt_pass.getText().trim().isEmpty()) {
                txt_userName.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Password");
                return false;
            }
            if (!rdo_nam.isSelected() && !rdo_nu.isSelected()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính");
                return false;
            }
            if (!rdo_daNghi.isSelected() && !rdo_dangLam.isSelected()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái");
                return false;
            }
             if (!rdo_nv.isSelected() && !rdo_ql.isSelected()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò");
                return false;
            }
//            for (NhanVien nv : service.findAll()) {
//                if (nv.getEmail().equals(txt_email.getText().trim())) {
//                    JOptionPane.showMessageDialog(this, "Email đã tồn tại, vui lòng nhập email khác");
//                    return false;
//                }
//                if (nv.getSdt().equals(txt_sdt.getText().trim())) {
//                    JOptionPane.showMessageDialog(this, "SĐT đã tồn tại, vui lòng nhập SĐT khác");
//                    return false;
//                }
//                if (nv.getUserName().equals(txt_userName.getText().trim())) {
//                    JOptionPane.showMessageDialog(this, "UserName đã tồn tại, vui lòng nhập UserName khác");
//                    return false;
//                }
//            }
            String chkemail = "\\w+@\\w{3,8}+\\.+\\w{2,4}";
            String chksdt = "\\d{10}";
            if (!txt_email.getText().matches(chkemail)) {
                txt_email.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng email");
                return false;
            }
            if (!txt_sdt.getText().matches(chksdt)) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng SDT");
                return false;
            }
        } catch (Exception e) {
            System.out.println("Lỗi validate");
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CLEAR;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_daNghi;
    private javax.swing.JRadioButton rdo_dangLam;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JRadioButton rdo_nv;
    private javax.swing.JRadioButton rdo_ql;
    private javax.swing.JTable tbl_listNV;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_find;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_ngayDK;
    private javax.swing.JTextField txt_ngaySua;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
