/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.NhaCungCap;
import QLNhaCungCap.QLNhaCungCap;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class JFrameNCC extends javax.swing.JFrame {

    private final QLNhaCungCap data = new QLNhaCungCap();
//    private final FormSanPhamChiTiet formSanPhamChiTiet = new FormSanPhamChiTiet();
    /**
     * Creates new form JFrameNCC
     */
    public JFrameNCC() {
        initComponents();
        this.setLocationRelativeTo(null);
        LocalDate ngayHT = LocalDate.now();
        txtNgayTao.setText(ngayHT + "");
        txtNgayTao.setEditable(false);
        txtNgaySua.setEditable(false);
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        txtNgaySua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdoHopTac = new javax.swing.JRadioButton();
        btnThem1 = new javax.swing.JButton();
        rdoNgungHopTac = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnSua1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQLNCC = new javax.swing.JTable();
        lblMa = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSua2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel9.setText("TRANG THAI");

        jLabel11.setText("NGAY SUA");

        txtNgayTao.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("TIM KIEM"));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNgaySua.setBackground(new java.awt.Color(204, 204, 204));
        txtNgaySua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySuaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("QUAN LY NHA CUNG CAP");

        buttonGroup1.add(rdoHopTac);
        rdoHopTac.setSelected(true);
        rdoHopTac.setText("HOP TAC");

        btnThem1.setBackground(new java.awt.Color(204, 0, 204));
        btnThem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem1.setForeground(new java.awt.Color(255, 255, 255));
        btnThem1.setText("THEM");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNgungHopTac);
        rdoNgungHopTac.setText("NGUNG HOP TAC");

        jLabel7.setText("MA");

        btnSua1.setBackground(new java.awt.Color(204, 0, 204));
        btnSua1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua1.setForeground(new java.awt.Color(255, 255, 255));
        btnSua1.setText("SUA");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        jLabel8.setText("TEN");

        tblQLNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MA", "TEN", "TRANG THAI", "NGAY TAO", "NGAY SUA"
            }
        ));
        tblQLNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLNCCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQLNCC);

        lblMa.setText("...");

        jLabel10.setText("NGAY TAO");

        btnSua2.setBackground(new java.awt.Color(204, 0, 204));
        btnSua2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua2.setForeground(new java.awt.Color(255, 255, 255));
        btnSua2.setText("CLEAR");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoHopTac)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNgungHopTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTen)
                                                    .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNgayTao)
                                                    .addComponent(txtNgaySua, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnThem1)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSua1)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSua2)))
                                        .addGap(141, 141, 141))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNgaySua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdoHopTac)
                    .addComponent(rdoNgungHopTac))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1)
                    .addComponent(btnSua1)
                    .addComponent(btnSua2))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgaySuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySuaActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        for (NhaCungCap ncc1 : data.getAll()) {
            if (ncc1.getTenNCC().equalsIgnoreCase(txtTen.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Tên nhà cung cấp trùng, vui lòng nhập lại");
                return;
            }
        }
        NhaCungCap ncc = check();
        if (ncc == null) {
            return;
        }
        data.add(ncc);
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        btnSua2ActionPerformed(evt);
        fillTable();
//        formSanPhamChiTiet.setNCC();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        int row = tblQLNCC.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa","Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        NhaCungCap ncc = checkUpdate();
        if (ncc == null) {
            return;
        }
        data.update(row, ncc);
        JOptionPane.showMessageDialog(this, "Sửa thành công");
        btnSua2ActionPerformed(evt);
        fillTable();
//        formSanPhamChiTiet.setNCC();
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void tblQLNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLNCCMouseClicked
        // TODO add your handling code here:
        int row = tblQLNCC.getSelectedRow();
        lblMa.setText(tblQLNCC.getValueAt(row, 0).toString());
        txtTen.setText(tblQLNCC.getValueAt(row, 1).toString());
        if (tblQLNCC.getValueAt(row, 2).equals("HOP TAC")) {
            rdoHopTac.setSelected(true);
        } else {
            rdoNgungHopTac.setSelected(true);
        }
        if (tblQLNCC.getValueAt(row, 3) == null) {
            txtNgayTao.setText(null);
        } else {
            txtNgayTao.setText(tblQLNCC.getValueAt(row, 3).toString());
        }
        if (tblQLNCC.getValueAt(row, 4) == null) {
            txtNgaySua.setText(null);
        } else {
            txtNgaySua.setText(tblQLNCC.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_tblQLNCCMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        ArrayList<NhaCungCap> ds = data.search(txtTimKiem.getText());
        DefaultTableModel dtm = (DefaultTableModel) this.tblQLNCC.getModel();
        dtm.setRowCount(0);
        for (NhaCungCap ncc : ds) {
            Object[] rowData = {
                ncc.getMa(),
                ncc.getTenNCC(),
                ncc.getTrangThai() == false ? "NGUNG HOP TAC" : "HOP TAC",
                ncc.getNgayTao(),
                ncc.getNgaySua()
            };
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        // TODO add your handling code here:
      
        txtTen.setText("");
        lblMa.setText("");
        rdoHopTac.setSelected(true);
    }//GEN-LAST:event_btnSua2ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrameNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrameNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrameNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrameNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameNCC().setVisible(true);
//            }
//        });
//    }

    private NhaCungCap check() {
        String tenNCC = txtTen.getText();
        String ngayT = txtNgayTao.getText();
        String ngayS = txtNgaySua.getText();

        if (tenNCC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên","Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
        NhaCungCap ncc = new NhaCungCap();
        ncc.setTenNCC(tenNCC);
        if (rdoHopTac.isSelected()) {
            ncc.setTrangThai(true);
        } else {
            ncc.setTrangThai(false);
        }
        ncc.setNgayTao(ngayT);
        ncc.setNgaySua(ngayS);
        return ncc;
    }

    private NhaCungCap checkUpdate() {
        int ma = Integer.parseInt(lblMa.getText());
        String tenNCC = txtTen.getText();
        String ngayT = txtNgayTao.getText();
        LocalDate ngaySua = LocalDate.now();
        txtNgaySua.setText(ngaySua + "");
        String ngayS = txtNgaySua.getText();

        if (tenNCC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên","Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        NhaCungCap ncc = new NhaCungCap();
        ncc.setMa(ma);
        ncc.setTenNCC(tenNCC);
        if (rdoHopTac.isSelected()) {
            ncc.setTrangThai(true);
        } else {
            ncc.setTrangThai(false);
        }
        ncc.setNgayTao(ngayT);
        ncc.setNgaySua(ngayS);
        return ncc;
    }

    void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.tblQLNCC.getModel();
        dtm.setRowCount(0);
        for (NhaCungCap ncc : data.getAll()) {
            Object[] rowData = {
                ncc.getMa(),
                ncc.getTenNCC(),
                ncc.getTrangThai() == false ? "NGUNG HOP TAC" : "HOP TAC",
                ncc.getNgayTao(),
                ncc.getNgaySua()
            };
            dtm.addRow(rowData);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMa;
    private javax.swing.JRadioButton rdoHopTac;
    private javax.swing.JRadioButton rdoNgungHopTac;
    private javax.swing.JTable tblQLNCC;
    private javax.swing.JTextField txtNgaySua;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
